server:
  port: 16886
  servlet:
    context-path: /aiTest
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false

spring:
  application:
    name: general-spring-ai
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  ai:
    openai:
      base-url: https://api.openai.com
      api-key: key
      model: gpt-4o-mini
      temperature: 0.7
      max-tokens: 2000
      connect-timeout: 600000
      socket-timeout: 600000
      retry:
        max-attempts: 3
        initial-interval: 1000
        multiplier: 2.0
        max-interval: 10000