server:
  port: 8080
  servlet:
    context-path: /aiTest
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false

spring:
  application:
    name: general-spring-ai
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  ai:
    ollama:
      base-url: http://192.188.80.165:11434
      timeout: 30000
      chat:
        model: qwen2.5-coder:32b
    performance:
      test:
        concurrent-users: 10
        requests-per-user: 5
        request-timeout: 30000
        test-prompt: "测试大模型的性能和响应时间"
        collect-detailed-metrics: true
        result-output-dir: "performance-test-results"


